### PR TITLE
fix: replaced single date picker for date range picker in the lab results component.

### PR DESCRIPTION
**Pull request by amosmachora**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

In this PR I have added a date range picker to allow for fetching of data by date ranges. As highlighted by @donaldkibet [here](https://openmrs.atlassian.net/browse/O3-3916) it makes it easier to track and follow up on ordered test results.

While I was at it I refactored the loading state a little bit to make the UI consistent between loading and loaded states. to reduce the amount of 'layout shift' that happens.

## Screenshots

image

## Related Issue

https://openmrs.atlassian.net/browse/O3-3916

### CODE REVIEW

**Comment by ojwanganto** [comment]
Do you mind attaching a video as well?

**Comment by donaldkibet** [comment]
Thanks @amosmachora just one comment, can we have the filter persist across the tabs i.e if we filter test order for a certain during we should retain that range when we transition the tests to picked up orders

**Review by donaldkibet — APPROVED** [review]

**Comment by donaldkibet** [comment]
@amosmachora please follow up with a PR

**Comment by amosmachora** [comment]
Got it @donaldkibet

**Pull request merged**
