### PR TITLE
(fix) O3-3809: failing lab results request form and cleaned up code to avoid duplication

### PR DESCRIPTION
**Pull request by amosmachora**
## Requirements

- [X] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

In this PR I have fixed an issue that occurred when a user tries to submti lab results from the laboratory esm. The backend returned error 400 which I found out was due to a missing `Orderer` object.

Also following a discussion on [slack](https://openmrs.slack.com/archives/C02UNMKFH8V/p1723793493742759), I have removed the `result-form-component.tsx` from the esm laboratory app. The reason was that this component was an exact duplicate of an existing one on the esm patient chart app. The gist is we instead just call the existing form. For more details please see [here.](https://openmrs.slack.com/archives/C02UNMKFH8V/p1723793493742759)

## Screenshots

https://github.com/user-attachments/assets/6606fee0-1f77-48d8-b772-d0610e1822e7

## Related Issue

https://openmrs.atlassian.net/browse/O3-3809

## Other

cc @ibacher @ojwanganto @donaldkibet @denniskigen

### CODE REVIEW

**Comment by gracepotma** [comment]
Thank you so much @amosmachora !

**Comment by ojwanganto** [comment]
@denniskigen @donaldkibet @ibacher - could you kindly help with reviews when you get a chance?

**Review by donaldkibet — APPROVED** [review]
Thanks @amosmachora! Should we include in the README that for this to work we have a dependency on `@openmrs/esm-patient-lab-order` package.

**Comment by amosmachora** [comment]
> Thanks @amosmachora! Should we include in the README that for this to work we have a dependency on `@openmrs/esm-patient-lab-order` package.

Probably a good idea. Will make a follow up PR if this one gets merged.

**Comment by denniskigen** [comment]
Thanks for this. There's some useful work that needs to be ported over from the deleted files. I've filed a PR [here](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1985) introducing those changes to the new form which is now the single source of truth for recording lab orders.

**Pull request merged**
